services:
  configserver:
    image: "rvinrajan3281/configserver:v1"
    container_name: configserver-ms
    ports:
      - "8099:8099"
    healthcheck:
      test: "curl --fail --silent localhost:8099/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  eurekaserver:
    image: "rvinrajan3281/eurekaserver:v1"
    container_name: eurekaserver-ms
    ports:
      - "9090:9090"
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8099/
    healthcheck:
      test: "curl --fail --silent localhost:9090/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      configserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-base-config


  accounts:
    image: "rvinrajan3281/accounts:v1"
    container_name: accounts-ms
    ports:
      - "8094:8094"
    environment:
      SPRING_APPLICATION_NAME: "accounts"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  cards:
    image: "rvinrajan3281/cards:v1"
    container_name: cards-ms
    ports:
      - "8093:8093"
    environment:
      SPRING_APPLICATION_NAME: "cards"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loans:
    image: "rvinrajan3281/loans:v1"
    container_name: loans-ms
    ports:
      - "8092:8092"
    environment:
      SPRING_APPLICATION_NAME: "loans"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loans1:
    image: "rvinrajan3281/loans:v1"
    container_name: loans-ms1
    ports:
      - "8098:8092"
    environment:
      SPRING_APPLICATION_NAME: "loans"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  eazybank:
    driver: "bridge"