services:
  rabbit:
    image: rabbitmq:3.13-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:
    image: "rvinrajan3281/configserver:v1"
    container_name: configserver-ms
    ports:
      - "8099:8099"
    healthcheck:
      test: "curl --fail --silent localhost:8099/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 700m
    extends:
      file: common-config.yml
      service: microservice-base-config

  eurekaserver:
    image: "rvinrajan3281/eurekaserver:v1"
    container_name: eurekaserver-ms
    ports:
      - "9090:9090"
    healthcheck:
      test: "curl --fail --silent localhost:9090/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 700m
    extends:
      file: common-config.yml
      service: microservice-base-config
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"

  accounts:
    image: "rvinrajan3281/accounts:v1"
    container_name: accounts-ms
    ports:
      - "8094:8094"
    environment:
      SPRING_APPLICATION_NAME: "accounts"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  cards:
    image: "rvinrajan3281/cards:v1"
    container_name: cards-ms
    ports:
      - "8093:8093"
    environment:
      SPRING_APPLICATION_NAME: "cards"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loans:
    image: "rvinrajan3281/loans:v1"
    container_name: loans-ms
    ports:
      - "8092:8092"
    environment:
      SPRING_APPLICATION_NAME: "loans"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  eazybank:
    driver: "bridge"